apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 2  # Adjust based on how many instances you want
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: pes1ug22cs154/url-shortener:latest  # Replace with your Docker image name
        ports:
        - containerPort: 5000  # Update if your app runs on a different port
        env:
        - name: REDIS_HOST
          value: redis  # Redis service name within the cluster
        - name: REDIS_PORT
          value: "6379"  # Redis default port

